### ISSUE TITLE
Support for members-injection methods for Scopes

### ISSUE THREAD

**Issue by larryng** [uber/motif#27]
Any plans to support [members-injection methods](https://google.github.io/dagger/api/2.6/dagger/Component.html#members-injection-methods)?  It'd be convenient to have while migrating old code.  As a workaround, I'm using a [Dagger Component as a child to the Motif Scope](https://github.com/uber/motif/blob/master/DAGGER.md#dagger-component-as-child-of-motif-scope), but that [requires adding provision methods to the Scope](https://google.github.io/dagger/api/2.6/dagger/Component.html#component-dependencies) which isn't great.

**Comment by Leland-Takamine** [comment]
Hey @larryng - Our general philosophy is to favor API simplicity over complete support for JSR 330 / Dagger features. Members-injection is a feature that we've specifically chosen to leave out. I feel especially bad about closing this one out since you've taken the time to submit a PR, which is very much appreciated. Although we can't accept this particular feature request, please continue submitting issues if you run into any other issues during your migration.

**Comment by larryng** [comment]
No problem @Leland-Takamine, thanks for the quick turnaround (even though I disagree with the decision).  Would you mind addressing my question [re: RIBs + Motif](https://github.com/uber/RIBs/issues/306) then?  I don't see how y'all are using the two together as they are now.
