### ISSUE TITLE
Recommended multi-module usage?

### ISSUE THREAD

**Issue by ursusursus** [uber/motif#30]
Hi,
I would like some clarification on how to best use this in gradle multimodule, since it uses subcomponents as chuld scopes.

Mostly, how would a :foo feature module access its scope instance?

I could see a interface (in :foo module) that would be partial RootScope which has FooScope builder method, which is then implemented by the actual RootScope.

Anyways, basically why were subcomponents chosen over dependant components

**Comment by Leland-Takamine** [comment]
Hi @ursusursus - You're right that Motif Scopes are similar to Subcomponents in that the parent declares its children (instead of children declaring their parents), but in fact under the hood Motif uses component dependencies. Let me try to answer your other question also:

> how would a :foo feature module access its scope instance?

Similar to Dagger Components, Motif Scope instances themselves are available on the graph. This is typically how I'd access the Scope instance:

```java
interface FooScope {

  @motif.Objects
  class Objects {
    
    FooController controller(FooScope scope) {
      return new FooController(scope);
    }
  }
}
```

With this setup, `FooController` above has an instance of `FooScope`. Please let me know if this addressed your question and if you have any others!

**Comment by Leland-Takamine** [comment]
Going to close this out but please feel free to open back up this didn't answer your question.
